//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBITest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long AccountNumber { get; set; }
        public string AccountType { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public string Status { get; set; }
        public decimal Balance { get; set; }
        public long BranchCode { get; set; }
        public long CustomerID { get; set; }
        public byte[] AddressProof { get; set; }
    }
}
