//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBITest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public long BranchCode { get; set; }
        public string BranchName { get; set; }
        public string CityName { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string BankerName { get; set; }
        public string BranchLogInID { get; set; }
        public string BranchPassword { get; set; }
        public string Email { get; set; }
    }
}
