//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBITest
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchTransferRequest
    {
        public int RequestID { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string Status { get; set; }
        public long AccountNumber { get; set; }
        public long FromBranch { get; set; }
        public long ToBranch { get; set; }
        public long CustomerID { get; set; }
    }
}
