//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBITest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime DOB { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string PermanentAddress { get; set; }
        public string CommunicationAddress { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string TransactionPassword { get; set; }
        public string Token { get; set; }
        public byte[] PhotoIDProof { get; set; }
    }
}
