//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBITest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public long LoanAccountNumber { get; set; }
        public decimal AnnualIncome { get; set; }
        public string LoanType { get; set; }
        public decimal Tenure { get; set; }
        public byte[] SalaryProof { get; set; }
    }
}
